package-lock.json, package.json, src/index.js
add modern-normalize, install husky, prettier
=> add devpendences

package-lock.json, package.json, src/components/LoginForm/LoginForm.jsx, src/components/RegisterForm/RegisterForm.jsx, src/components/dashboard/header/header.js, src/pages/loginPage.js, src/redux/authOperations.js, src/redux/authSlice.js, src/redux/store.js, yarn.lock
=> add authorization

src/components/RegisterForm/RegisterForm.jsx, src/components/RegisterForm/RegisterForm.module.css, src/pages/registerPage.js, src/pages/registerPage.module.css
=> Register page

package.json, src/components/LoginForm/LoginForm.jsx, src/components/RegisterForm/RegisterForm.jsx, src/components/dashboard/header/header.js, src/index.js, src/redux/auth/authOperations.js, src/redux/auth/authSlice.js, src/redux/store.js, src/redux/transactions/transactionOperations.js, src/redux/transactions/transactionSlice.js
added redux operations getTransactions and addTransaction
=> added redux operations getTransactions and addTransaction

src/components/dashboard/ballance/ballance.js, src/components/dashboard/header/header.js
додав ім"я користувача, його баланс, та логаут
=> add users balance and name, logot action

src/components/dashboard/ballance/ballance.js, src/redux/auth/authOperations.js, src/redux/transactions/transactionOperations.js, src/redux/transactions/transactionSlice.js
=> fix balance

src/components/App.jsx, src/redux/auth/authOperations.js, src/redux/auth/authSlice.js, src/redux/store.js, src/redux/transactions/transactionOperations.js
=> fix refresh current user

src/components/dashboard/ballance/ballance.module.css, src/components/dashboard/navMenu/navMenu.module.css, src/components/dashboard/transaction/TransactionDesk.module.css, src/pages/dashboard.js, src/pages/homePage.js, src/pages/homePage.module.css, src/pages/styles.module.css
=> mobileDesign done with small fixes

src/pages/styles.module.css
Fixed  height of transactions in mobile version
=> littlefixes

src/pages/statPage.js, src/pages/statPage.module.css
=> update stat's styles

package-lock.json, package.json, src/components/LoginForm/LoginForm.jsx, src/components/RegisterForm/RegisterForm.jsx, src/components/dashboard/currency/currency.js, src/components/modal/modalAddTransaction/modalAddTransaction.js, src/components/spinner/spinner.js, src/redux/auth/authSlice.js
=> add spinner

src/pages/styles.module.css
=> height fix

src/components/modalLogout/modalLogout.js, src/pages/homePage.js, src/redux/auth/authSlice.js, src/redux/statistics/statisticsSlice.js, src/redux/transactions/transactionSlice.js
=> Fix spiner

src/components/modal/modalAddTransaction/modalAddTransaction.js, src/index.js
Reverts Aleksandr-Pod/FinalTeamProject#114
=> Revert "Formik - bad result"

src/components/LoginForm/LoginForm.jsx, src/components/RegisterForm/RegisterForm.jsx, src/pages/loginPage.js, src/pages/registerPage.js
=> change spinner in auth

src/components/App.jsx, src/redux/auth/authOperations.js, src/redux/statistics/statisticsOperations.js, src/redux/transactions/transactionOperations.js
=> added notifications

src/redux/statistics/statisticsOperations.js, src/redux/transactions/transactionSlice.js
fix loading transactions fon new user, removed message on receive statistic data.
=> fix loading transactions

src/components/dashboard/ballance/ballance.module.css, src/components/dashboard/currency/currency.module.css, src/components/dashboard/navMenu/navMenu.module.css, src/components/dashboard/navMenu/navMenuMobile.js, src/pages/homePage.module.css, src/pages/registerPage.module.css, src/pages/statPage.module.css
nav and currency fixed, with backgrounds
=> all bugs fixed

src/components/modal/modalAddTransaction/modalAddTransaction.js
В формі додавання транзакції дозволено вибір будь-якого числа поточного місяця
=> add change any date for current month

src/components/footer/footer.js, src/components/footer/footer.module.css, src/components/period/period.js, src/pages/dashboard.js
add footer and fix point 2 from testers
=> add footer

src/components/RegisterForm/RegisterForm.jsx
Дозволено ім"я від 1 до 12 символів
=> validation name length in reg form

src/components/loginForm/loginForm.jsx, src/pages/loginPage.js, src/pages/registerPage.js, src/redux/auth/authOperations.js
=> fix spiner on register and login
